### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by ambitiuswisdom** [Autodesk/Aurora#22]
Hello there,

I'm trying to build Aurora v23.03 in Windows 11, currently failing on Installing externals

This is the log:

```c:\Aurora>python Scripts\installExternals.py ..\AuroraExternals -v -v

Building with settings:
    Aurora source directory       c:\Aurora
    Externals source directory    c:\AuroraExternals\src
    Externals install directory   c:\AuroraExternals
    Build directory               c:\AuroraExternals\build
    CMake generator               Default
    CMake toolset                 Default

    Variant                       Release
    Dependencies                  stb, tinygltf, tinyobjloader, boost, tbb, OpenEXR, OpenImageIO, MaterialX, OpenSubdiv, USD, Slang, glew, GLFW, cxxopts, gtest

STATUS: Installing stb...
INFO: Running "git clone --recurse-submodules https://github.com/nothings/stb.git stb-5736b15f7ea0ffb08dd38af21067c314d6a3aae9"
Traceback (most recent call last):
  File "c:\Aurora\Scripts\installExternals.py", line 609, in GitCloneSHA
    Run("git clone --recurse-submodules {url} {folder}".format(url=url, folder=cloneDir))
  File "c:\Aurora\Scripts\installExternals.py", line 250, in Run
    p = subprocess.Popen(shlex.split(cmd), stdout=subprocess.PIPE,
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System can not find specified file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Aurora\Scripts\installExternals.py", line 1721, in <module>
    dep.installer(context,
  File "c:\Aurora\Scripts\installExternals.py", line 967, in InstallSTB
    with CurrentWorkingDirectory(GitCloneSHA(STB_URL, STB_SHA, STB_FOLDER, context)):
  File "c:\Aurora\Scripts\installExternals.py", line 618, in GitCloneSHA
    url=url, tag=tag, err=e))
NameError: name 'tag' is not defined
ERROR: name 'tag' is not defined
```

Is there anything wrong in code or just my fault?

**Comment by andy-shiue-autodesk** [comment]
Hi, could you try the git clone command directly to see if that works?

> git clone --recurse-submodules https://github.com/nothings/stb.git stb-5736b15f7ea0ffb08dd38af21067c314d6a3aae9

I wonder if you problem a long path name issue on Windows. If you google "long path name windows 11" you will find some links explaining the issue.
